def clasificar_mora_gob(dato, tipo_impuesto):
    mora = []
    if isinstance(tipo_impuesto, int):
        tipo_impuesto = str(tipo_impuesto)
    if tipo_impuesto == '0':
        mora = [
            {'cta_ingreso': '111110', 'nombre': 'Impuesto Sobre Bienes Inmuebles', 'valor': dato['bi']},
            {'cta_ingreso': '111111', 'nombre': 'Impuesto Personal', 'valor': dato['ip']},
            {'cta_ingreso': '111112', 'nombre': 'Impuesto a establecimientos Industriales', 'valor': dato['ind']},
            {'cta_ingreso': '111113', 'nombre': 'Impuesto a establecimientos Comerciales', 'valor': dato['com']},
            {'cta_ingreso': '111114', 'nombre': 'Impuesto a Establecimientos de Servicios', 'valor': dato['ser']},
            {'cta_ingreso': '111115', 'nombre': 'Impuesto por extraccion de recursos', 'valor': dato['pecuario']},
            {'cta_ingreso': '111116', 'nombre': 'Impuesto por extraccion de recursos', 'valor': dato['extraccion']},
            {'cta_ingreso': '111117', 'nombre': 'Impuesto Selectivo a las Telecomunicaciones', 'valor': dato['extraccion']},
            {'cta_ingreso': '111118', 'nombre': 'Servicios Municipales','valor': dato['servicios']},
            {'cta_ingreso': '111119', 'nombre': 'Tasas Municipales', 'valor': dato['tasas']},
            {'cta_ingreso': '112120', 'nombre': 'Multas', 'valor': dato['multas']},
            {'cta_ingreso': '112121', 'nombre': 'Recargos', 'valor': dato['recargos']},
            {'cta_ingreso': '11212201', 'nombre': 'Recuperación de Impuestos','valor': dato['recuperacionbi']},
            {'cta_ingreso': '11212202', 'nombre': 'Recuperación Impuesto Personal','valor': dato['recuperacionip']},
            {'cta_ingreso': '11212203', 'nombre': 'Recuperación Establecimientos Industriales','valor': dato['recuperacionind']},
            {'cta_ingreso': '11212204', 'nombre': 'Recuperación Establecimientos Comerciales','valor': dato['recuperacioncom']},
            {'cta_ingreso': '11212205', 'nombre': 'Recuperación Establecimientos Servicios','valor': dato['recuperacionser']},
            {'cta_ingreso': '11212206', 'nombre': 'Recuperación de Impuestos de Extracción','valor': dato['recuperacionexctracion']},
            {'cta_ingreso': '11212207', 'nombre': 'Recuperación IST (Telecomunicaciones)','valor': dato['recuperacionslectivo']},
            {'cta_ingreso': '11212209', 'nombre': 'Recuperación de Billares', 'valor': dato['recuperacionBillares']},
            {'cta_ingreso': '11212210', 'nombre': 'Recuperación Tasas-Derechos Municipales', 'valor': dato['recuperacionTasas']},
            {'cta_ingreso': '112123', 'nombre': 'Recuperación de Servicios', 'valor': dato['recuperacionSp']},
            {'cta_ingreso': '112124', 'nombre': 'Recuperacion Alquileres', 'valor': dato['recuperacionAl']},
            {'cta_ingreso': '112125', 'nombre': 'Alquileres', 'valor': dato['alquileres']},
            {'cta_ingreso': '112126', 'nombre': 'Intereses', 'valor': dato['intereses']},
            {'cta_ingreso': '112126', 'nombre': 'Contribucion', 'valor': dato['otros_ingresos']},
            {'cta_ingreso': '212222', 'nombre': 'Contribucion por mejoras y otros','valor': dato['otros_ingresos']},
            {'cta_ingreso': '112127', 'nombre': 'Descuentos', 'valor': dato['descuentos']},
        ]
    elif tipo_impuesto == '1':
        mora = [
            {'cta_ingreso': '111110', 'nombre': 'Impuesto Sobre Bienes Inmuebles', 'valor': dato['bi']},
            {'cta_ingreso': '111118', 'nombre': 'Servicios Municipales','valor': dato['servicios']},
            {'cta_ingreso': '111119', 'nombre': 'Tasas Municipales','valor': dato['tasas']},
            {'cta_ingreso': '112120', 'nombre': 'Multas','valor': dato['multas']},
            {'cta_ingreso': '11212201', 'nombre': 'Recuperación de Impuestos','valor': dato['recuperacionbi']},
            {'cta_ingreso': '11212210', 'nombre': 'Recuperación Tasas-Derechos Municipales', 'valor': dato['recuperacionTasas']},
            {'cta_ingreso': '112123', 'nombre': 'Recuperación de Servicios','valor': dato['recuperacionSp']},
            {'cta_ingreso': '112124', 'nombre': 'Recuperacion Alquileres', 'valor': dato['recuperacionAl']},
            {'cta_ingreso': '112125', 'nombre': 'Alquileres', 'valor': dato['alquileres']},
            {'cta_ingreso': '112121', 'nombre': 'Recargos','valor': dato['recargos']},
            {'cta_ingreso': '112126', 'nombre': 'Intereses','valor': dato['intereses']},
            {'cta_ingreso': '112127', 'nombre': 'Descuentos','valor': dato['descuentos']},
            {'cta_ingreso': '212222', 'nombre': 'Contribucion por mejoras y otros','valor': dato['otros_ingresos']},
        ]
    elif tipo_impuesto == '2' or tipo_impuesto == '3':
        mora = [
            {'cta_ingreso': '111112', 'nombre': 'Impuesto a establecimientos Industriales', 'valor': dato['ind']},
            {'cta_ingreso': '111113', 'nombre': 'Impuesto a establecimientos Comerciales', 'valor': dato['com']},
            {'cta_ingreso': '111114', 'nombre': 'Impuesto a Establecimientos de Servicios', 'valor': dato['ser']},
            {'cta_ingreso': '111116', 'nombre': 'Impuesto por extraccion de recursos', 'valor': dato['extraccion']},
            {'cta_ingreso': '111117', 'nombre': 'Impuesto Selectivo a las Telecomunicacione', 'valor': dato['extraccion']},
            {'cta_ingreso': '111118', 'nombre': 'Servicios Municipales','valor': dato['servicios']},
            {'cta_ingreso': '111119', 'nombre': 'Tasas Municipales', 'valor': dato['tasas']},
            {'cta_ingreso': '112120', 'nombre': 'Multas', 'valor': dato['multas']},
            {'cta_ingreso': '112121', 'nombre': 'Recargos', 'valor': dato['recargos']},
            {'cta_ingreso': '11212203', 'nombre': 'Recuperación Establecimientos Industriales','valor': dato['recuperacionind']},
            {'cta_ingreso': '11212204', 'nombre': 'Recuperación Establecimientos Comerciales','valor': dato['recuperacioncom']},
            {'cta_ingreso': '11212205', 'nombre': 'Recuperación Establecimientos Servicios','valor': dato['recuperacionser']},
            {'cta_ingreso': '11212206', 'nombre': 'Recuperación de Impuestos de Extracción','valor': dato['recuperacionexctracion']},
            {'cta_ingreso': '11212207', 'nombre': 'Recuperación IST (Telecomunicaciones)','valor': dato['recuperacionslectivo']},
            {'cta_ingreso': '11212209', 'nombre': 'Recuperación de Billares', 'valor': dato['recuperacionBillares']},
             {'cta_ingreso': '11212210', 'nombre': 'Recuperación Tasas-Derechos Municipales', 'valor': dato['recuperacionTasas']},
            {'cta_ingreso': '112123', 'nombre': 'Recuperación de Servicios', 'valor': dato['recuperacionSp']},
            {'cta_ingreso': '112124', 'nombre': 'Recuperacion Alquileres', 'valor': dato['recuperacionAl']},
            {'cta_ingreso': '112125', 'nombre': 'Alquileres', 'valor': dato['alquileres']},
            {'cta_ingreso': '112126', 'nombre': 'Intereses', 'valor': dato['intereses']},
            {'cta_ingreso': '112127', 'nombre': 'Descuentos', 'valor': dato['descuentos']},
        ]
    elif tipo_impuesto == '4':
        mora = [
            {'cta_ingreso': '111111', 'nombre': 'Impuesto Personal', 'valor': dato['ip']},
            {'cta_ingreso': '111116', 'nombre': 'Impuesto por extraccion de recursos', 'valor': dato['extraccion']},
            {'cta_ingreso': '111117', 'nombre': 'Impuesto Selectivo a las Telecomunicacione', 'valor': dato['extraccion']},
            {'cta_ingreso': '111118', 'nombre': 'Servicios Municipales','valor': dato['servicios']},
            {'cta_ingreso': '111119', 'nombre': 'Tasas Municipales', 'valor': dato['tasas']},
            {'cta_ingreso': '112120', 'nombre': 'Multas', 'valor': dato['multas']},
            {'cta_ingreso': '112121', 'nombre': 'Recargos', 'valor': dato['recargos']},
            {'cta_ingreso': '11212202', 'nombre': 'Recuperación Impuesto Personal','valor': dato['recuperacionip']},
            {'cta_ingreso': '11212206', 'nombre': 'Recuperación de Impuestos de Extracción','valor': dato['recuperacionexctracion']},
            {'cta_ingreso': '11212207', 'nombre': 'Recuperación IST (Telecomunicaciones)','valor': dato['recuperacionslectivo']},
            {'cta_ingreso': '11212210', 'nombre': 'Recuperación Tasas-Derechos Municipales', 'valor': dato['recuperacionTasas']},
            {'cta_ingreso': '112123', 'nombre': 'Recuperación de Servicios', 'valor': dato['recuperacionSp']},
            {'cta_ingreso': '112124', 'nombre': 'Recuperacion Alquileres', 'valor': dato['recuperacionAl']},
            {'cta_ingreso': '112125', 'nombre': 'Alquileres', 'valor': dato['alquileres']},
            {'cta_ingreso': '212222', 'nombre': 'Contribucion por mejoras y otros','valor': dato['otros_ingresos']},
            {'cta_ingreso': '112126', 'nombre': 'Intereses', 'valor': dato['intereses']},
            {'cta_ingreso': '112127', 'nombre': 'Descuentos', 'valor': dato['descuentos']},
        ]

    elif tipo_impuesto == '5':
        mora = [
            {'cta_ingreso': '11111801', 'nombre': 'Servicio de Agua','valor': dato['agua']},
            {'cta_ingreso': '11111802', 'nombre': 'Servicio de Alcantarillado','valor': dato['alcantarillado']},
            {'cta_ingreso': '11111803', 'nombre': 'Servicio de Alumbrado Publico','valor': dato['alumbrado']},
            {'cta_ingreso': '11111804', 'nombre': 'Servicio de Tren de Aseo','valor': dato['tren']},
            {'cta_ingreso': '11111805', 'nombre': 'Servicio de Conexiones Y Reconexiones','valor': dato['conexiones']},
            {'cta_ingreso': '11111806', 'nombre': 'Servicio de Bomberos','valor': dato['bomberos']},
            {'cta_ingreso': '11111807', 'nombre': 'Rastro Publico','valor': dato['rastro']},
            {'cta_ingreso': '11111808', 'nombre': 'Transporte de Carne','valor': dato['trasporte_carme']},
            {'cta_ingreso': '11111809', 'nombre': 'Balanza Municpal','valor': dato['balanza']},
            {'cta_ingreso': '11111810', 'nombre': 'Limpieza de solares baldíos','valor': dato['limpieza_solares']},
            {'cta_ingreso': '11111811', 'nombre': 'Aseo de parques, calles y avenidas ','valor': dato['aseo_parques_ave']},
            {'cta_ingreso': '11111812', 'nombre': 'Limpieza de cementerio','valor': dato['limpieza_cementerio']},
            {'cta_ingreso': '11111813', 'nombre': 'Servicios secretariales municipales','valor': dato['servicios_secretaria']},
            {'cta_ingreso': '11111814', 'nombre': 'Servicios de muellaje','valor': dato['muellaje']},
            {'cta_ingreso': '11111815', 'nombre': 'Servicios de Turismo','valor': dato['turismo']},
            {'cta_ingreso': '11111816', 'nombre': 'Seguridad Ciudadana','valor': dato['seguridad']},
            {'cta_ingreso': '11111820', 'nombre': 'Tasa Ambiental','valor': dato['tasa_ambiental']},
            {'cta_ingreso': '11111899', 'nombre': 'Otros servicios municipales','valor': dato['otros_servicios']},
            {'cta_ingreso': '111119', 'nombre': 'Tasas Municipales', 'valor': dato['tasas']},
            {'cta_ingreso': '112120', 'nombre': 'Multas', 'valor': dato['multas']},
            {'cta_ingreso': '112121', 'nombre': 'Recargos', 'valor': dato['recargos']},
            {'cta_ingreso': '112123', 'nombre': 'Recuperación de Servicios', 'valor': dato['recuperacionSp']},
            {'cta_ingreso': '112126', 'nombre': 'Intereses', 'valor': dato['intereses']},
            {'cta_ingreso': '112127', 'nombre': 'Descuentos', 'valor': dato['descuentos']},
        ]
    else:
        mora = [
            {'cta_ingreso': '111110', 'nombre': 'Impuesto Sobre Bienes Inmuebles', 'valor': dato['bi']},
            {'cta_ingreso': '111111', 'nombre': 'Impuesto Personal', 'valor': dato['ip']},
            {'cta_ingreso': '111112', 'nombre': 'Impuesto a establecimientos Industriales', 'valor': dato['ind']},
            {'cta_ingreso': '111113', 'nombre': 'Impuesto a establecimientos Comerciales', 'valor': dato['com']},
            {'cta_ingreso': '111114', 'nombre': 'Impuesto a Establecimientos de Servicios', 'valor': dato['ser']},
            {'cta_ingreso': '111115', 'nombre': 'Impuesto por extraccion de recursos', 'valor': dato['pecuario']},
            {'cta_ingreso': '111116', 'nombre': 'Impuesto por extraccion de recursos', 'valor': dato['extraccion']},
            {'cta_ingreso': '111117', 'nombre': 'Impuesto Selectivo a las Telecomunicacione', 'valor': dato['extraccion']},
            {'cta_ingreso': '111118', 'nombre': 'Servicios Municipales','valor': dato['servicios']},
            {'cta_ingreso': '111119', 'nombre': 'Tasas Municipales', 'valor': dato['tasas']},
            {'cta_ingreso': '112120', 'nombre': 'Multas', 'valor': dato['multas']},
            {'cta_ingreso': '112121', 'nombre': 'Recargos', 'valor': dato['recargos']},
            {'cta_ingreso': '11212201', 'nombre': 'Recuperación de Impuestos','valor': dato['recuperacionbi']},
            {'cta_ingreso': '11212202', 'nombre': 'Recuperación Impuesto Personal','valor': dato['recuperacionip']},
            {'cta_ingreso': '11212203', 'nombre': 'Recuperación Establecimientos Industriales','valor': dato['recuperacionind']},
            {'cta_ingreso': '11212204', 'nombre': 'Recuperación Establecimientos Comerciales','valor': dato['recuperacioncom']},
            {'cta_ingreso': '11212205', 'nombre': 'Recuperación Establecimientos Servicios','valor': dato['recuperacionser']},
            {'cta_ingreso': '11212206', 'nombre': 'Recuperación de Impuestos de Extracción','valor': dato['recuperacionexctracion']},
            {'cta_ingreso': '11212207', 'nombre': 'Recuperación IST (Telecomunicaciones)','valor': dato['recuperacionslectivo']},
            {'cta_ingreso': '11212209', 'nombre': 'Recuperación de Billares', 'valor': dato['recuperacionBillares']},
            {'cta_ingreso': '11212210', 'nombre': 'Recuperación Tasas-Derechos Municipales', 'valor': dato['recuperacionTasas']},
            {'cta_ingreso': '112123', 'nombre': 'Recuperación de Servicios', 'valor': dato['recuperacionSp']},
            {'cta_ingreso': '112124', 'nombre': 'Recuperacion Alquileres', 'valor': dato['recuperacionAl']},
            {'cta_ingreso': '112125', 'nombre': 'Alquileres', 'valor': dato['alquileres']},
            {'cta_ingreso': '112126', 'nombre': 'Intereses', 'valor': dato['intereses']},
            {'cta_ingreso': '212222', 'nombre': 'Contribucion por mejoras y otros','valor': dato['otros_ingresos']},
            {'cta_ingreso': '112127', 'nombre': 'Descuentos', 'valor': dato['descuentos']},
        ]
    return mora
