def clasificar_mora_sami(dato, tipo_impuesto):
    mora = []
    if isinstance(tipo_impuesto, int):
        tipo_impuesto = str(tipo_impuesto)
    if tipo_impuesto == '0':
        mora = [
            {'cta_ingreso': '111110',
                'nombre': 'Impuesto Sobre Bienes Inmuebles', 'valor': dato['bi']},
            {'cta_ingreso': '111111',
                'nombre': 'Impuesto Personal', 'valor': dato['bi']},
            {'cta_ingreso': '111112',
                'nombre': 'Impuesto a establecimientos Industriales', 'valor': dato['ic']},
            {'cta_ingreso': '111113',
                'nombre': 'Impuesto a establecimientos Comerciales', 'valor': dato['com']},
            {'cta_ingreso': '111114',
                'nombre': 'Impuesto a Establecimientos de Servicios', 'valor': dato['ser']},
            {'cta_ingreso': '111115', 'nombre': 'Impuesto Pecuario',
                'valor': dato['pecuario']},
            {'cta_ingreso': '111119', 'nombre': 'Tasas Municipales',
                'valor': dato['tasas']},
            {'cta_ingreso': '111118', 'nombre': 'Servicios Municipales',
                'valor': dato['servicios']},
            {'cta_ingreso': '112120', 'nombre': 'Multas',
                'valor': dato['multas']},
            {'cta_ingreso': '112122', 'nombre': 'Recuperacion de Impuestos',
                'valor': dato['recuperacion']},
            {'cta_ingreso': '112123', 'nombre': 'Recuperacion de Servicios',
                'valor': dato['recuperacionSp']},
            {'cta_ingreso': '112126', 'nombre': 'Intereses',
                'valor': dato['intereses']},
            {'cta_ingreso': '112121', 'nombre': 'Recargos',
                'valor': dato['recargos']},
        ]
    elif tipo_impuesto == '1':
        mora = [
            {'cta_ingreso': '111110',
                'nombre': 'Impuesto Sobre Bienes Inmuebles', 'valor': dato['bi']},
            {'cta_ingreso': '111119', 'nombre': 'Tasas Municipales',
                'valor': dato['tasas']},
            {'cta_ingreso': '111118', 'nombre': 'Servicios Municipales',
                'valor': dato['servicios']},
            {'cta_ingreso': '112120', 'nombre': 'Multas',
                'valor': dato['multas']},
            {'cta_ingreso': '112122', 'nombre': 'Recuperacion de Impuestos',
                'valor': dato['recuperacion']},
            {'cta_ingreso': '112123', 'nombre': 'Recuperacion de Servicios',
                'valor': dato['recuperacionSp']},
            {'cta_ingreso': '112126', 'nombre': 'Intereses',
                'valor': dato['intereses']},
            {'cta_ingreso': '112121', 'nombre': 'Recargos',
                'valor': dato['recargos']},
        ]
    elif tipo_impuesto == '2' or tipo_impuesto == '3':
        mora = [
            {'cta_ingreso': '111112',
                'nombre': 'Impuesto a establecimientos Industriales', 'valor': dato['ic']},
            {'cta_ingreso': '111113',
                'nombre': 'Impuesto a establecimientos Comerciales', 'valor': dato['com']},
            {'cta_ingreso': '111114',
                'nombre': 'Impuesto a Establecimientos de Servicios', 'valor': dato['ser']},
            {'cta_ingreso': '111119', 'nombre': 'Tasas Municipales',
                'valor': dato['tasas']},
            {'cta_ingreso': '111118', 'nombre': 'Servicios Municipales',
                'valor': dato['servicios']},
            {'cta_ingreso': '112120', 'nombre': 'Multas',
                'valor': dato['multas']},
            {'cta_ingreso': '112122', 'nombre': 'Recuperacion de Impuestos',
                'valor': dato['recuperacion']},
            {'cta_ingreso': '112123', 'nombre': 'Recuperacion de Servicios',
                'valor': dato['recuperacionSp']},
            {'cta_ingreso': '112126', 'nombre': 'Intereses',
                'valor': dato['intereses']},
            {'cta_ingreso': '112121', 'nombre': 'Recargos',
                'valor': dato['recargos']},
        ]
    elif tipo_impuesto == '4':
        mora = [
            {'cta_ingreso': '111111',
                'nombre': 'Impuesto Personal', 'valor': dato['bi']},
            {'cta_ingreso': '111119', 'nombre': 'Tasas Municipales',
                'valor': dato['tasas']},
            {'cta_ingreso': '111118', 'nombre': 'Servicios Municipales',
                'valor': dato['servicios']},
            {'cta_ingreso': '112120', 'nombre': 'Multas',
                'valor': dato['multas']},
            {'cta_ingreso': '112122', 'nombre': 'Recuperacion de Impuestos',
                'valor': dato['recuperacion']},
            {'cta_ingreso': '112123', 'nombre': 'Recuperacion de Servicios',
                'valor': dato['recuperacionSp']},
            {'cta_ingreso': '112126', 'nombre': 'Intereses',
                'valor': dato['intereses']},
            {'cta_ingreso': '112121', 'nombre': 'Recargos',
                'valor': dato['recargos']},
        ]

    elif tipo_impuesto == '5':
        mora = [
            {'cta_ingreso': '111119', 'nombre': 'Tasas Municipales',
                'valor': dato['tasas']},
            {'cta_ingreso': '111118', 'nombre': 'Servicios Municipales',
                'valor': dato['servicios']},
            {'cta_ingreso': '112120', 'nombre': 'Multas',
                'valor': dato['multas']},
            {'cta_ingreso': '112123', 'nombre': 'Recuperacion de Servicios',
                'valor': dato['recuperacionSp']},
            {'cta_ingreso': '112126', 'nombre': 'Intereses',
                'valor': dato['intereses']},
            {'cta_ingreso': '112121', 'nombre': 'Recargos',
                'valor': dato['recargos']},
        ]
    else:
        mora = [
            {'cta_ingreso': '111110',
                'nombre': 'Impuesto Sobre Bienes Inmuebles', 'valor': dato['bi']},
            {'cta_ingreso': '111111',
                'nombre': 'Impuesto Personal', 'valor': dato['bi']},
            {'cta_ingreso': '111112',
                'nombre': 'Impuesto a establecimientos Industriales', 'valor': dato['ic']},
            {'cta_ingreso': '111113',
                'nombre': 'Impuesto a establecimientos Comerciales', 'valor': dato['com']},
            {'cta_ingreso': '111114',
                'nombre': 'Impuesto a Establecimientos de Servicios', 'valor': dato['ser']},
            {'cta_ingreso': '111115', 'nombre': 'Impuesto Pecuario',
                'valor': dato['pecuario']},
            {'cta_ingreso': '111119', 'nombre': 'Tasas Municipales',
                'valor': dato['tasas']},
            {'cta_ingreso': '111118', 'nombre': 'Servicios Municipales',
                'valor': dato['servicios']},
            {'cta_ingreso': '112120', 'nombre': 'Multas',
                'valor': dato['multas']},
            {'cta_ingreso': '112122', 'nombre': 'Recuperacion de Impuestos',
                'valor': dato['recuperacion']},
            {'cta_ingreso': '112123', 'nombre': 'Recuperacion de Servicios',
                'valor': dato['recuperacionSp']},
            {'cta_ingreso': '112126', 'nombre': 'Intereses',
                'valor': dato['intereses']},
            {'cta_ingreso': '112121', 'nombre': 'Recargos',
                'valor': dato['recargos']},
        ]
    return mora
